#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use App\Command\RunServerCommand;

$application = new Application('Simple SSO toolkit', '1.0.0');
$application->add(new RunServerCommand());
$application->run();